---
- name: Instal dependencies
  homebrew:
    name: openjdk@11
    state: present

- name: "Make sure {{ install_dir.linux }} directory exists"
  file:
    path: "{{ install_dir.macosx }}"
    state: directory

- name: "Download and unarchive Android SDK command line tools"
  unarchive: 
    copy: no
    src: "{{ download_url.macosx }}"
    dest: "{{ install_dir.macosx }}"
    force: yes
    mode: 0755

- name: "Install required packages"
  shell: "echo y | {{ install_dir.macosx }}/tools/bin/sdkmanager {{ required_packages | map('quote') | join(' ') }}"

- name: Add command line tools to PATH
  copy:
    dest: /etc/profile.d/sdkmanager.sh
    content: 'PATH=$PATH:{{ install_dir.macosx }}/tools/bin/'