version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins/jenkins.yaml:/tmp/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/tmp/jenkins.yaml
    restart: always
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - '81:81'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
