pipeline {
    agent {
        node {
            label 'ubuntu'
            customWorkspace 'image_builder'
        }
    }

    parameters {
        text(name: 'imageName', defaultValue: '', description: 'Image name to be created')
    }

    stages {
        stage ('Build Image') {
            steps {
                script {
                    def packerAnsbile = docker.build("packer-ansible", 'image-builder')
                    // Mounting passwd and groups along with overriding HOME environment variable are workarounds for ansible and packer failing to connect
                    packerAnsbile.inside("-e \"HOME=${WORKSPACE}\" -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group") {
                        withCredentials([azureServicePrincipal('azure-service-principal')]) {
                            sh 'packer build -color=false image-builder/ubuntu-packer.json'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}