pipeline {
    agent {
        node {
            label 'ubuntu'
            customWorkspace 'image_builder'
        }
    }

    stages {
        stage ('Build Image') {
            steps {   
                script {

                    def packerAnsbile = docker.build("packer-ansible", 'image-builder') 

                    packerAnsbile.inside {
                        withCredentials([azureServicePrincipal('azure-service-principal')]) {
                            sh 'packer build image-builder/ubuntu-packer.json'
                        }
                    }

                }
                
            }
            post {
                always {
                    cleanWs()
                }
            }
        }
    }
}