credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "github-credentials"
          password: ${GITHUB_PASS}
          scope: GLOBAL
          username: ${GITHUB_USER}
      - azure:
          azureEnvironmentName: "Azure"
          clientId: ${AZURE_CLIENT_ID}
          clientSecret: ${AZURE_CLIENT_SECRET}
          id: "azure-service-principal"
          scope: GLOBAL
          subscriptionId: ${AZURE_SUBSCRIPTION_ID}
          tenant: ${AZURE_TENANT_ID}
      - usernamePassword:
          id: "jenkins-agents-credentials"
          password: ${JENKINS_AGENT_PASS}
          scope: GLOBAL
          username: ${JENKINS_AGENT_USER}
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  clouds:
  - azureVM:
      azureCredentialsId: "azure-service-principal"
      cloudName: "AwesomeCloud"
      cloudTags:
      - name: "department"
        value: "devops"
      configurationStatus: "pass"
      deploymentTimeout: 1200
      maxVirtualMachinesLimit: 10
      newResourceGroupName: "jenkins-agents"
      resourceGroupReferenceType: "new"
      vmTemplates:
      - agentLaunchMethod: "SSH"
        agentWorkspace: "/tmp/jenkins"
        builtInImage: "Ubuntu 16.04 LTS"
        credentialsId: "jenkins-agents-credentials"
        diskType: "managed"
        doNotUseMachineIfInitFails: true
        enableMSI: false
        enableUAMI: false
        ephemeralOSDisk: false
        executeInitScriptAsRoot: true
        imageTopLevelType: "basic"
        installDocker: true
        installGit: false
        installMaven: false
        javaPath: "java"
        labels: "ubuntu"
        location: "North Europe"
        newStorageAccountName: "realjenkinsstorag"
        noOfParallelJobs: 1
        osDiskSize: 0
        osType: "Linux"
        preInstallSsh: true
        retentionStrategy:
          azureVMCloudRetentionStrategy:
            idleTerminationMinutes: 10
        shutdownOnIdle: false
        storageAccountNameReferenceType: "new"
        storageAccountType: "Premium_LRS"
        templateDisabled: false
        templateName: "ubuntu"
        usageMode: "Only build jobs with label expressions matching this node"
        usePrivateIP: false
        virtualMachineSize: "Standard_B1s"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "master"
  - name: "ubuntu"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  appInsightsGlobalConfig:
    appInsightsEnabled: true
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  casCGlobalConfig:
    configurationPath: "/tmp/jenkins.yml"
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:\r\n\r\nCheck\
      \ console output at $BUILD_URL to view the results."
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    useSsl: false
    watchingEnabled: false
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:81/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "admin@domain.local"
    url: "http://localhost:81/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - file: /tmp/casc/jobs-seed.groovy
groovy:
  - file: /tmp/casc/enable-security.groovy